export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_REQUEST_SUCCESS = "ALL_PRODUCT_REQUEST_SUCCESS";
export const ALL_PRODUCT_REQUEST_FAIL = "ALL_PRODUCT_REQUEST_FAIL";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const SET_ERROR = "SET_ERROR";
export const SET_LOADING = "SET_LOADING";
export const SET_PRODUCT = "SET_PRODUCT";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_FAIL = "REGISTER_FAIL";
